name: Email Notification

on:
  push:
    branches:
      - main
      - feature_a
      - feature_b

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Cambios subidos a rama ${{ github.ref_name }}
          to: eddysanchez2003eddy@gmail.com
          from: GitHub Actions
          body: |
            Se han subido cambios a la rama ${{ github.ref_name }}.